version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: installing git
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                sudo pip install awscli
                sudo apt-get install git
                sudo apt-get install python3
                python --version
                sudo pip install awscli              
            fi
      - run:
          name: installing docker 
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
                sudo apt-get update
                sudo apt-get install -y docker-ce
                sudo usermod -a -G docker ubuntu
                docker info
            fi
      - checkout
      - run:
          name: Docker Image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                sudo pwd
                sudo ls -al
                mv /home/circleci/project/Project1 /home/circleci/project/project1
                cd /home/circleci/project/project1
                sudo docker build -t project1 .
            fi
      - run:
          name: "Log in to AWS ECR"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                eval $(aws ecr get-login --no-include-email --region us-west-2)
            fi
          
      - run:
          name: Pushing Image
          command: |  
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                cd /home/circleci/project/project1
                sudo docker images
                sudo pwd
                sudo touch image.txt
                sudo chmod 755 image.txt
                sudo docker tag project1:latest $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/zephyrecr:latest
                sudo docker push $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/zephyrecr:latest
                echo "Pushed new image" > image.txt
                aws s3 rm s3://zephyrbucketp3 --recursive
                aws s3 cp image.txt s3://zephyrbucketp3
            fi

            
