version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: cibuilds/hugo:0.49 # the primary container, where your job's commands are run
    working_directory: ~/project
    steps:
      - run: apk update && apk add git
      - run: git submodule sync && git submodule update --init
      - run:
          name: install AWS CLI (first install pip, the Python package manager)
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli