version: 2
jobs:
  build:
    machine: true
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - run: apt-get install git
      - checkout #this is to checkout
      - run:
          name: install hugo 
          command: |
           wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.deb
           apt-get install dpkg
           dpkg -i hugo_0.49_Linux-64bit.deb

       